sudo: false
language: python
python:
  - 2.7
  - 3.5
os:
  - linux

install:
  - pip install tox-travis
  - pip install codecov

script:
  - tox
  - make .coverage

notifications:
  email: false

after_success:
  - codecov
